### ISSUE TITLE
[JNPCT] Create registration form

### ISSUE THREAD

**Issue by vinayvenu** [avniproject/jnpct#1]
Please look at https://docs.google.com/spreadsheets/d/1rxddSJUw7vQ_6TEdPYkT5_fF0K8BUQajnIBum34dLqc/edit#gid=1377233168 for details

**Comment by garimadosar5** [comment]
QA Notes - 
- Mobile number question, add the data validation.
- Aadhar Card Number, add the validation.

**Comment by shubhangipatil** [comment]
Both validations done
