### ISSUE TITLE
[JNPCT] Newborn/Child PNC Form

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#11]
https://docs.google.com/spreadsheets/d/1rxddSJUw7vQ_6TEdPYkT5_fF0K8BUQajnIBum34dLqc/edit#gid=87032227

**Comment by nupoorkhandelwal** [comment]
Q1 . Has child breathing regularly   ? **Missing**

**Comment by sachsk** [comment]
Fixed all issue

**Comment by nupoorkhandelwal** [comment]
Q13 . Does blood coming out from any part of body ( cord ,head ,mouth, anus ) ?>>
 ** Getting displayed in second visit**
Q 17 Count the breaths in one minute ? ( if it is 60 or more than 60 then refer to hospital .)>>
**Not showing system recommendation on 60 **

Q 26 Looking at condition of umbelicus   
( if other than nornal then apply 0.25%GV lotion, give first dose of cotri and refer)
**This sysytem recommendation is not showing**

**Comment by sachsk** [comment]
fixed

**Comment by garimadosar5** [comment]
QA Notes - 
- "First Examination" section is not showing
- "Explain mother to increase the frequency of breastfeeding" this counselling point is coming for all the cases. [on the last page of encounter].
-

**Comment by sachsk** [comment]
@garimadosar5 
1)"First Examination" section shows  only if delivery occurs at home and for the first visit only

**Comment by garimadosar5** [comment]
QA Notes 2 - 
- The form is crashing on question 63. "Date of referral".

**Comment by sachsk** [comment]
@garimadosar5 
Fixed
