### ISSUE TITLE
[JNPCT Support] PNC visit got scheduled on back date

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/jnpct#110]
Support ticket - https://avni.freshdesk.com/a/tickets/2539

PNC visit for the individual is getting scheduled on back date --
uuid of the individual: 51152a9f-3713-460f-804f-0b0d7f5a027c

- [x] Investigate the root cause and fix the issue

**Comment by vedfordev** [comment]
added !programEncounter.programEnrolment.hasEncounter('Child PNC Cluster Incharge','Child PNC Cluster Incharge-2') in visit schedule condition where Child PNC Cluster Incharge-2 is schedule
