### ISSUE TITLE
[JNPCT] Child Followup

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#12]
https://docs.google.com/spreadsheets/d/1rxddSJUw7vQ_6TEdPYkT5_fF0K8BUQajnIBum34dLqc/edit#gid=1354684055

**Comment by nupoorkhandelwal** [comment]
Q 54	Whether child stiil get breastfeed 	If Age < 2 Years
** Condition not working**

Q 38	if child age is 2-6 month then according to age and weight in which grade	Autocalculated
** Add auto-calculation for grade. Remove options int he question** (eg. This is done in CHETNA-SNEHA impl)

Q37	weight for child 
** It is showing for child > 6 months also** (use only one weight concept for child in any condition )

Q45 and Q46 ** Q45 is numeric field and based on it's value, Q46 value will be auto-populated**

**Comment by garimadosar5** [comment]
QA Notes - 
- Qus 67 and 68, change the condition. show these questions if 66 is YES.
