### ISSUE TITLE
[JNPCT MCH]: Changes in ANC for Saheli and Supervisor

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/jnpct#135]
- [x] Changes to be made in JNPCT UAT first
- [x] Move the bundle from production to UAT and do the changes
- [x] Changes in the form are highlighted in Green.
- [x] [Form Link](https://docs.google.com/spreadsheets/d/1rxddSJUw7vQ_6TEdPYkT5_fF0K8BUQajnIBum34dLqc/edit?gid=1889956416#gid=1889956416)
- [x] The question "Saheli has written the expected date of delivery on the beneficiary's house wall?" should come in the **ANC Saheli Form and to be answered by Saheli**
- [x] Once answer to this question "Saheli has written the expected date of delivery on the beneficiary's house wall?" in the ANC Saheli form is "Yes" **show in the ANC form which is scheduled for Supervisor question "Supervisor has verified that Saheli has written expected date of delivery on beneficiary's house wall?"**

**Comment by vedfordev** [comment]
@kameshbhariya check anc form. both questions' condition in card and requirement sheet are different. currently made changes as per requirement sheet. Move card to on hold.
