### ISSUE TITLE
[JNPCT MCH]: Add counselling points for Child Follow up

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/jnpct#137]
- [x] Changes to be done in UAT first. Please upload the bundle from JNPCT production to JNPCT UAT and then do the changes

- [x] Counselling points to be added in all the below forms

1. Child Follow up Saheli
2. Child Follow up Cluster Incharge 
3. Child Follow up

- [x] [Add counselling points for Child follow-up (0-6 Months)](https://docs.google.com/spreadsheets/d/1yMq0aBYuDo6fKFWyzHuAwro9QmCJHg9m/edit?gid=788436145#gid=788436145&range=3:16)
- [x] [Add counselling points for Child follow-up (7 Months to 12 Months)](https://docs.google.com/spreadsheets/d/1yMq0aBYuDo6fKFWyzHuAwro9QmCJHg9m/edit?gid=788436145#gid=788436145&range=17:33)
- [x] [Add counselling points for Child follow-up 2 years or more](https://docs.google.com/spreadsheets/d/1yMq0aBYuDo6fKFWyzHuAwro9QmCJHg9m/edit?gid=788436145#gid=788436145&range=34:41)

**Comment by Dinesh2019** [comment]
@AnjaliBhagabati
 
- [ ] if the child age > 12 month and < 2years. do we need to add any counselling points 
- [ ] And for 7 to 12 months some sentences ended as or do we need any word to complete the sentence or it is fine.

**Comment by AnjaliBhagabati** [comment]
@vedfordev @Dinesh2019 

- [ ]  if the child age > 12 month and < 2years. do we need to add any counselling points : Not required

 

- [ ] And for 7 to 12 months some sentences ended as or do we need any word to complete the sentence or it is fine.: Let it be as it is

**Comment by vedfordev** [comment]
@Dinesh2019 
Check point and if it is not qa fail then move the card.
