### ISSUE TITLE
[JNPCT MCH]: Add counselling points for Child PNC

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/jnpct#138]
- [x]  Changes to be done in UAT first. Please upload the bundle from JNPCT production to JNPCT UAT and then do the changes

- [x] Counselling points to be added in all the below forms

1. Child PNC
2. Child PNC Saheli
3. Child PNC Cluster In Charge

- [x] [Add counselling points for Child PNC (0-6 Months)](https://docs.google.com/spreadsheets/d/1yMq0aBYuDo6fKFWyzHuAwro9QmCJHg9m/edit?gid=788436145#gid=788436145&range=3:16)
- [x] [Add counselling points for Child PNC (0-2 Months)](https://docs.google.com/spreadsheets/d/1yMq0aBYuDo6fKFWyzHuAwro9QmCJHg9m/edit?gid=788436145#gid=788436145&range=42:71)

**Comment by vedfordev** [comment]
@kameshbhariya / @nupoorkhandelwal Please check below point.

1. For both org english language is not available. 
2. I checked their are some translation done on english key in english language to describe points. 
3. I have done changes same way. 

So if we don't want english language we need to remove english latter.
