### ISSUE TITLE
[JNPCT MCH]: Child PNC Visit - Add decision rules for medicine recommendations along with dosage.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/jnpct#139]
- [ ] Changes to be done in UAT first. Please upload the bundle from JNPCT production to JNPCT UAT and then do the changes

 

- [x] Medicine Recommendation to be added in all the below forms

Child PNC
Child PNC Saheli
Child PNC Cluster In Charge

[Add decision rules for medicine recommendations along with dosage under the Counsel Mother
](https://docs.google.com/spreadsheets/d/1yMq0aBYuDo6fKFWyzHuAwro9QmCJHg9m/edit?gid=1698951868#gid=1698951868)

- [x] Once the completion of Child PNC visit, if the child's age is between 0-29 days then recommend "Cotrimoxazole" with 1.5 ml of dosage and show symptoms as "There are fewer than 10 red spots containing pus on the skin."

- [x] Once the completion of Child PNC visit, if the child's age is between 30-59 days then recommend "Cotrimoxazole" with 2.5 ml of dosage and show symptoms as "There are fewer than 10 red spots containing pus on the skin."

- [ ] Once the completion of Child Follow-up, if the child's age is between 2-12 months then recommend "Cotrimoxazole" with 2.5 ml of dosage and show symptoms as "Chest indrawing or Fast breathing"

**Comment by AnjaliBhagabati** [comment]
@nupoorkhandelwal can we add the  "Medicine Recommendation by creating a separate section called "Medicine Recommention and add these rules.
Vedant has done it in [this card ](https://app.zenhub.com/workspaces/avni-impl--support-5cf8e458bf08585333fd64ac/issues/gh/avniproject/jnpct/140)
