### ISSUE TITLE
[JNPCT MCH]: Child Follow-up - Add decision rules for medicine recommendations along with dosage.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/jnpct#140]
- [x]  Changes to be done in UAT first. Please upload the bundle from JNPCT production to JNPCT UAT and then do the changes
- [x]  Medicine Recommendation to be added in all the below forms

Child Follow up Saheli
Child Follow up Cluster Incharge
Child Follow up

- [x] Create a section called "Medicine Recommention  and add these rules. 
- [x] [Add decision rules for medicine recommendations along with dosage.

(https://docs.google.com/spreadsheets/d/1yMq0aBYuDo6fKFWyzHuAwro9QmCJHg9m/edit?gid=1698951868#gid=1698951868)

- [x] Once the completion of Child Follow-up, if the child's age is between 12 months - 5 years then recommend "Cotrimoxazole" with 5 ml of dosage and show symptoms as "Chest indrawing or Fast breathing"

- [x] Once the completion of Child Follow-up, if the child's age is between 2 months - 3 years then recommend "Paracetamol" with 5 ml of dosage and show symptoms as "Fever"

- [x] Once the completion of Child Follow-up, if the child's age is between 3 months - 5 years then recommend "Paracetamol" with 10 ml of dosage and show symptoms as "Fever"

**Comment by vedfordev** [comment]
### Dev Note:

1. As per discussion with @AnjaliBhagabati @nupoorkhandelwal created new concept and added concept for Medicine recommendation
2. Tried with system generated logic but that not worked. So as per discussed with @sachsk added logic with the help of model methods.
