### ISSUE TITLE
[JNPCT MCH]: Changes in individual form for new born.

### ISSUE THREAD

**Issue by kameshbhariya** [avniproject/jnpct#141]
- [ ] Changes to be made in UAT.
- [ ] The form will stay as it is. However, in the case of a newborn infant aged 0 month to 1 year, autofetch a few details from the mother's individual registration form.
- [ ] [Analysis Link](https://docs.google.com/spreadsheets/d/1rxddSJUw7vQ_6TEdPYkT5_fF0K8BUQajnIBum34dLqc/edit?gid=1377233168#gid=1377233168)

**Tech notes**

- [ ] First create a individual subject type called Mother, which will give all subject types who are above 18 years of age.
- [ ] Try fetching individual details of the selected subject type

**Comment by nupoorkhandelwal** [comment]
This is technically not possible.

**Comment by Dinesh2019** [comment]
- [x] We are missing to show the sub-caste - As discussed, this will show up as soon as there is some user input on the form
- [x] Specially abled - Please specify is not auto-fetched - **How can child have same disability as Mother?**
- [ ] Also we have shown the individual whose delivery encounter is completed and whose age should be >15 years

**Comment by Dinesh2019** [comment]
@kameshbhariya @nupoorkhandelwal as discussed with Kamesh removed this Specially abled - Please specify is not auto-fetched.

And also we have shown the individual whose delivery encounter is completed and whose age should be >15 years this is not possible
