### ISSUE TITLE
[JNPCT] Visit Schedule - Child

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#30]
- Newborn 
- Child Followup

https://docs.google.com/spreadsheets/d/1rxddSJUw7vQ_6TEdPYkT5_fF0K8BUQajnIBum34dLqc/edit#gid=740855390

Schedules - 
- Child Birth - **DONE**
- Newborn - Normal - **Not DONE**
- Newborn - Low Birth Weight (if Birth weight is less than 2 Kgs) - **Not DONE**
- Child Followup (2 Months to 6 months) - **Not DONE**
- Child Followup (7 Months to  24 months) - Normal - **NOT DONE**
- Child Followup (2 Years to 5 Years) - Normal - **DONE**
- Child Followup (7 Months to  24 months) - SAM - **DONE**
- Child Followup (2 Years to 5 Years) - SAM - **DONE**
- Child Followup (7 Months to  24 months) - MAM - **DONE**
- Child Followup (2 Years to 5 Years) - MAM - **DONE**

##### Test SCenarios - 
1. The child got enrolled during birth
2. The child got enrolled one month after birth
3. The child got enrolled at 2 years of age.
4. The child got enrolled seven months after birth.
4. The child got enrolled with low birth weight.
5. he child got enrolled on 100th day after birth.
6. What happens if the last visit gets cancelled after the time of the next visit is passed. - **Failed.**
7. What if

**Comment by garimadosar5** [comment]
QA Notes - 
- If the child is enrolled after 90 days of birth, then no followup visit gets scheduled.

**Comment by garimadosar5** [comment]
QA Notes - 2
- If I have filled birth form and CHild PNC 1 and then edit Birth form, another PNC 1 get scheduled.
-

**Comment by garimadosar5** [comment]
QA Notes - 16 Jan 20.
- If I cancel a visit after the scheduled date of next visit is over then it does not schedule any other visit. What will they do in that case?
- Childbirth on 15 Jan 20. Enrolment on 16 Jan 20. Birth form got scheduled on 16 Jan 20. Child is LBW wit 1.8 Kgs of weight. Child PNC gets scheduled on 30 Jan. it is neither an LBW logic nor a normal weight logic.

**Comment by nupoorkhandelwal** [comment]
@garimadosar5 
If I cancel a visit after the scheduled date of next visit is over then it does not schedule any other visit. What will they do in that case? -- For which visits? Specify an individual for which this is happening?
