### ISSUE TITLE
[JNPCT] UAT changes in Mother Module

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/jnpct#31]
1) ANC form >> Check condition for anemic - **NOT DONE**
2) ANC form >>  Check condition for question complete hospital checkup done  - **NOT DONE**

3) In Delivery form >> Add units to all  the weight(numeric) fields of Newborn1/2/3 and stillborn1/2/3 - **DONE**

4 ) In Abortion form>> Period of gestation in weeks at the time of Abortion/MTP >> make this auto calculated - **DONE**

**Comment by garimadosar5** [comment]
QA Notes - 

- ANC form >> Check condition for anemic - **NOT DONE**
-  ANC form >>  Check condition for question complete hospital checkup done  - **NOT DONE**
- In delivery form Weight of stillborn2 question is always saying even if there is no Stillbirth as a pregnancy outcome.
