### ISSUE TITLE
[JNPCT] Growth chart plot is not showing.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#34]
![Screen Shot 2019-12-26 at 5.17.34 PM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/04b23e3d-c5db-4979-a420-580d2fc2a5be)

Cases -Baby Shah and Piya Pal

**Comment by sachsk** [comment]
i have change concept from current weight to "**Weight**" because of graph take values from concepts i.e. **Weight** & **Height**

**Comment by garimadosar5** [comment]
QA Notes - 
- It is not taking birth weight form birth form.

**Comment by sachsk** [comment]
fixed. now it takes birth weight  from birth form also
