### ISSUE TITLE
[JNPCT UAT Feedback after user training] 

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/jnpct#41]
1.  In individual registration form -occupation of husband is there only so we add husband /father .
2.     ANC form - vitals- temperature range is specified.
3.     ANC form - vitals -height range is added for high risk identification.
4.     In ANC form -Lab dignostic- one new question is added -does laboratory test done and skip logic along with
5.     skip logic changes for all question related to USG report  in ANC form.
6.     In delivery form- medical detail-delivery outcome  -2 option are removed .
7.     In mother PNC - Vitals- temperature range specified .
8.     in delivery form -weeks of gestation -option are specified for more understanding.
**These values we get calculated from the base** **So won't be able to update them**
9.     Mother PNC form- danger sign - burning micturation question is removed because it repeated in same form.
10.     In ABORTION form-place of abortion - OPTION  are changed.
11.     In new born new form two new sub question are added for diarrhea and pustules with logic .
12.     New born new -place of refer options are updated.
13.     in eligible couple form -summary show different date format in case of LMP. for that refer img.1
14.     in child follow up form we complete the visit and going to save form app will be stuck . refer img 2 
15.     In child follow up -ask about main symptoms - count breath in one minute .here we provided high risk condition though app does not show respiratory rate is high as per age .

**Comment by garimadosar5** [comment]
QA Notes - 
- Skip based on questions - "Dose Laboratory test done?" and "Complete hospital checkup done " are not working.
 -
