### ISSUE TITLE
[JNPCT] UAT Feedback -2

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/jnpct#42]
1. In requirement sheet we already provided respiratory rate range as per age though app does not count as high respiratory rate for child more than 2 month age . **Less than 2 months age (60) Check for all Child program forms**
 2. HB range is specified in requirement sheet  so diagnosis will be expected to show as per requirement in both ANC and Mother PNC visit. **Add new conditions**
3.  3 new sub question is added in child exit and child cancel form . Add Death related fields in Cancel nd Exit
4.  3 new sub question is added in mother exit and mother cancel form . **Add Death related fields in Cancel nd Exit**
5. Some form when to show or  hide will be discussed in meet. **1. Hide Delivery and Abortion from unplanned if already a Delivery/Abortion is done 2.Unhide Child Followup Visit if age is greater than 2 months. 3. Unhide Unplanned Child PNC if less than 2 months.**
6. In abortion followup form -danger sign- any vaginal problem- **Option are updated. Remove one option.check req.**
7. In ANC registration form -service provided- **Change TT as TD**. Update as mentioned in req
8. One new question is Added in ANC form -Hb measured by color scale . Add this numeric field and respective High Risk Conditions
9. In Birth form -Place of birth - New option are added .As per req.
10. In newborn new form -examine child for other danger sign - if yes then How many -option are added instead of writing number.**As per req.**
11. In child followup form- check for malnutrition -does child referred to cmtc-  **skip logic updated  .Show only if MUAC is SAM**
12.  **Add check to Program Enrolment eligibility check**. Mother Program - If Age is greater than 15 and Female.
13. Eligible Couple - If Age is greater than 15 and Female.
14. Child - If Age is less than equal to 5 yrs.
15. Check if PNC is getting scheduled even if age of child is greater than 8 days.

**Comment by garimadosar5** [comment]
QA Notes - 
- Point 3 and 4 skip logic is not working for cancel form.

**Comment by nupoorkhandelwal** [comment]
@garimadosar5  In Child Followup Form >> A new auto calculated field 'Nutritional Status according to weight' and height ' is added under check for malnutrition for child above 6 months. Initially there was only 'Nutritional status according to weight and age'.

**Comment by nupoorkhandelwal** [comment]
Point 1 is not done. Case "Nihal Naresh Vasav" Village - Vadijangal-3, Age 23 months. Breath count = 50 But showing normal. - CHILD FOLLOWUP form - NOT DONE
![screenshot-2020-06-28_14.34.08.938.png](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/9fae5086-a832-43e7-86f0-e99105aa4fd8)



Current nutritional status according to weight and height is not getting calculated in CHILD FOLLOWUP form even for children more than 6 months of age.
![screenshot-2020-06-28_14.24.51.888.png](https://images.zenhubusercontent.com/5d1469c9b0b5db61870d0f5c/a9ec45c2-66ac-4801-a37f-6fe05d1c2256)
