### ISSUE TITLE
[JNPCT] Add new vaccines to the existing Vaccination checklist

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/jnpct#43]
https://drive.google.com/drive/u/0/folders/1Gd3F8-GDOx3RhsIfEMLFPXz2ZwEDiVJu

**Comment by nupoorkhandelwal** [comment]
1. Rota -Same schedule as Pentavalent
2. Update Measeles to Measeles Rubella
3. JE - Refer IHMP
4. PCV Refer given schedule
5. Confirm Vitamin A doses 
6. Confirm PCV overdue date
7. DPT - Check if IHMP has
8. Confirm if we need vaccines for 5-6 and 10-16
9. FIPV  same as PCV schedule

**Comment by nupoorkhandelwal** [comment]
@garimadosar5  Have made these vaccine related changes in the JNPCT UAT org. 
U can use id -admin@jnpctuat /password to test this.

**Comment by garimadosar5** [comment]
QA Notes - 
- Pentavalent, Rota and other vaccines that are dependent on previous dosage, do not get scheduled after the previous one is done.
- It does not update vaccination checklist with the time. Vaccines for 9 months and 16 months never get scheduled.
Case - Sejal Shaheb
