### ISSUE TITLE
[JNPCT][REPORT] Delivery care

### ISSUE THREAD

**Issue by vindeolal** [avniproject/jnpct#45]
Report 3 in the sheet
https://docs.google.com/spreadsheets/d/1rilYb_F-zWMTyiYdXjHHmIoAiLCe_ok8/edit#gid=1840403879

**Comment by garimadosar5** [comment]
QA Notes - 
- Place of delivery, what is `Not Decided`. there are only three options in place of delivery question - Home, Hospital, On the way.

**Comment by vindeolal** [comment]
@garimadosar5 
- ```Not yet decided``` is an option in the form
[POD.png](https://images.zenhubusercontent.com/5d0b116e2fff8629577fc2d4/858c402c-92c8-47b2-b3a0-c429e661b409)
- Filters were not given by them when we started this report. PHC is not included because we show all the list in report and there is no point in showing that. We might need to add more filters, once they confirm.
