### ISSUE TITLE
[JNPCT][Report] Registration of Pregnant Women

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#47]
Aggregate - https://docs.google.com/spreadsheets/d/1rilYb_F-zWMTyiYdXjHHmIoAiLCe_ok8/edit#gid=1955342939
Line list - https://docs.google.com/spreadsheets/d/1MIBqA9bNq-QUjYS8_NL5NVeBnhydoJVX/edit?dls=true

**QA Checklist -** 
- [x] Percentage Calculation
- [x] Check for Column name and Indicator Name
- [x] Check for 100% sun for percentage, if applicable
- [x] All the filters are there.
- [x] Line List - Check for all the columns
- [x] Line List - Column names are, as mentioned in the requirement sheet.
- [x] cases are pointed to UAT.

**Comment by nupoorkhandelwal** [comment]
As per earlier requirements PHC and Subcenter were not there as part of linelist.

Will be adding them to the linelist in card "Anemia status of women in ANC and PNC"
