### ISSUE TITLE
[JNPCT][Report] Current ANC and delivered women

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#48]
Aggregate Report - https://docs.google.com/spreadsheets/d/1rilYb_F-zWMTyiYdXjHHmIoAiLCe_ok8/edit#gid=767144781

Line List  for Actionable- https://docs.google.com/spreadsheets/d/1MIBqA9bNq-QUjYS8_NL5NVeBnhydoJVX/edit?dls=true
Line list for Achievement - https://docs.google.com/spreadsheets/d/1MIBqA9bNq-QUjYS8_NL5NVeBnhydoJVX/edit#gid=1269848388

Steps - 
1. Actionable
2. Achievement
3.  Actionable  - Linelist
4. Achievement - Linelist

**QA Checklist -** 
- [ ] Percentage Calculation
- [x] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [ ] All the filters are there.
- [x] Line List - Check for all the columns
- [x] Line List - Column names are, as mentioned in the requirement sheet.
- [ ] cases are pointed to UAT.

**Comment by garimadosar5** [comment]
Estimate - 1.5

**Comment by garimadosar5** [comment]
QA Notes - 
- In actionable, current ANC - it is counting delivered women also. It should consider only ANC.

**Comment by 1t5j0y** [comment]
Filtered out women who have already delivered in both aggregate and linelist.
