### ISSUE TITLE
[JNPCT] ANC Form

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#5]
https://docs.google.com/spreadsheets/d/1rxddSJUw7vQ_6TEdPYkT5_fF0K8BUQajnIBum34dLqc/edit#gid=1889956416

**Comment by shubhangipatil** [comment]
skip logic Pending for these Questions
1. Blood Group 
2. T.T vaccine recieved ? (This is working for 1st visit,not working for (show this question repeatedly in anc visit utill mother received TT vaccine)
3.COUNSELLING(Below counselling question should be show only when 21 th week started, only once) - This is done but the below part of condition is not working any of the counselling question regarding preperation of delivery if ans is no then it should be shown in next visit.

**Comment by garimadosar5** [comment]
QA Notes - 
- "Does she eat all the snacks", show this question if "Does she get snacks from Anganwadi" is answered as YES.
-

**Comment by nupoorkhandelwal** [comment]
Question - "Place of delivery". Remove the option "On the Way"--**This is still remaining, except all other points are done.**
