### ISSUE TITLE
[JNPCT][Report] Child death/Maternal death

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#55]
Aggregate - https://docs.google.com/spreadsheets/d/1rilYb_F-zWMTyiYdXjHHmIoAiLCe_ok8/edit#gid=1094878303
Line list - Mother and child both

**QA Checklist -** 
- [ ] Percentage Calculation
- [x] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [x] All the filters are there.
- [x] Line List - Check for all the columns
- [x] Line List - Column names are, as mentioned in the requirement sheet.
- [x] cases are pointed to UAT.

**Comment by garimadosar5** [comment]
Estimate - 0.75

**Comment by 1t5j0y** [comment]
Pending linking to child linelist.

**Comment by garimadosar5** [comment]
QA Notes - 
Maternal death- line list is wrong. it shows all the PNC women.
![Screen Shot 2020-08-18 at 9.38.50 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/161c44f8-4971-472a-b214-4fd4940199de)

**Comment by 1t5j0y** [comment]
1. Fixed linelist linking. (New linelist created as existing one could not be reused).
2. Fixed age format in child linelist.
3. Renamed 'isexit' to 'Exited'
4. Linked name field to data entry app in both linelists and removed url column.
