### ISSUE TITLE
[JNPCT][Report] High Risk Delivery Care

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#57]
Aggregate - https://docs.google.com/spreadsheets/d/1rilYb_F-zWMTyiYdXjHHmIoAiLCe_ok8/edit#gid=1635133232

Line List - https://docs.google.com/spreadsheets/d/1MIBqA9bNq-QUjYS8_NL5NVeBnhydoJVX/edit#gid=495851789

**QA Checklist -** 
- [ ] Percentage Calculation
- [x] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [x] All the filters are there.
- [x] Line List - Check for all the columns
- [x] Line List - Column names are, as mentioned in the requirement sheet.
- [x] cases are pointed to UAT.

**Comment by garimadosar5** [comment]
estimate - 0.75

**Comment by garimadosar5** [comment]
QA Notes - 
- BMI, HB, twins are not getting calculated.
Case - Pahal Chavan

**Comment by sachsk** [comment]
-in case of pahal chavan BMI is 16.8 and our condition is BMI < 16
-for twins we are taking value from "Is there any danger sign?"
