### ISSUE TITLE
[JNPCT][Report] Expectant Mothers with no. of Risk

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#58]
Aggregate - https://docs.google.com/spreadsheets/d/1rilYb_F-zWMTyiYdXjHHmIoAiLCe_ok8/edit#gid=2059461877

Line List - https://docs.google.com/spreadsheets/d/1MIBqA9bNq-QUjYS8_NL5NVeBnhydoJVX/edit#gid=495851789

**QA Checklist -** 
- [ ] Percentage Calculation
- [ ] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [ ] All the filters are there.
- [ ] Line List - Check for all the columns
- [ ] Line List - Column names are, as mentioned in the requirement sheet.
- [ ] cases are pointed to UAT.

**Tech Tasks**
- [x] Write an aggregate query that returns a set of enrolments and number of each risk against each enl.
  - [x] Do wrap over this and do case when to remove multiple counting of risk and sum it to get total risks against each enl.
  - [x] Aggregate this further by using group by on phc and count(*) filter to get three columns(1 risk, 2-3 risk, > 3 risk).
  - [x] Add date filters on the enrolment date 
  - [x] Add ANC/Delivered filter
  - [x] Add Exited filter
  - [x] Add other filters
- [x] Copy existing ANC linelist report to create a linelist report for this card. 
  - [x] Add a column for high risks that will have a comma-separated list of high-risk conditions captured over all the ANC visits.
  - [x] Add a column that does the same calculation as an aggregate report for the number of high-risk conditions.
  - [x] Add filters.
- [x] Link aggregate report to linelist and add dynamic where

**Comment by hithacker** [comment]
moved it back to ready because I assigned it to myself and had moved it to in progress yday evening but didn't do any actual work and I may not be working today.
