### ISSUE TITLE
[JNPCT][Report]  Additional report 2  -  Growth Monitoring  (7 Months to 5 Years Child)

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#59]
Aggregate - https://docs.google.com/spreadsheets/d/1rilYb_F-zWMTyiYdXjHHmIoAiLCe_ok8/edit#gid=101122894

Line List - https://docs.google.com/spreadsheets/d/1MIBqA9bNq-QUjYS8_NL5NVeBnhydoJVX/edit#gid=157840825

**QA Checklist -** 
- [ ] Percentage Calculation
- [ ] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [ ] All the filters are there.
- [ ] Line List - Check for all the columns
- [ ] Line List - Column names are, as mentioned in the requirement sheet.
- [ ] cases are pointed to UAT.

### Tech Task

- [x] Create a report which shows the latest values for indicators
- [x] Compare the latest values to the latest-1 visit
- [x] Check last 6 months encounters if all are SAM then add count.
- [x] Add filters(date,Block, PHC, subcenter and Village,Exit/non-exit) in agg. and linelist
- [x] Create and link linelist with agg report

**Comment by garimadosar5** [comment]
QA Notes - 
- What is the logic for SAM since last 6 months. 
Currently case - Khushi K is in that column but that was enrolled on 14 Aug only. How it can be in SAM for last 6 months.

**Comment by sachsk** [comment]
fixed
