### ISSUE TITLE
[JNPCT] Program Summary 

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#6]
https://docs.google.com/spreadsheets/d/1rxddSJUw7vQ_6TEdPYkT5_fF0K8BUQajnIBum34dLqc/edit#gid=608373237

**Comment by garimadosar5** [comment]
QA Notes -

**Comment by nupoorkhandelwal** [comment]
Blood pressure is not showing for each visit. Only Latest is showing. -- **Uploaded changes to staging. Both the BP values will be shown when both values will be entered.**
