### ISSUE TITLE
[JNPCT][Report] Status of morbidity within 0 -59 days  children 

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#60]
Aggregate - https://docs.google.com/spreadsheets/d/1rilYb_F-zWMTyiYdXjHHmIoAiLCe_ok8/edit#gid=1947729321

Line List- https://docs.google.com/spreadsheets/d/1MIBqA9bNq-QUjYS8_NL5NVeBnhydoJVX/edit#gid=1897339731

**QA Checklist -** 
- [ ] Percentage Calculation
- [x] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [x] All the filters are there.
- [x] Line List - Check for all the columns
- [x] Line List - Column names are, as mentioned in the requirement sheet.
- [x] cases are pointed to UAT.

**Comment by sachsk** [comment]
Requirements are not clear.

**Comment by 1t5j0y** [comment]
Aggregate: Child - Morbidity Status Within 0-59 Days
Linelist: Child - Morbidity Status for Children 0-59 days Linelist

**Comment by 1t5j0y** [comment]
Added Sr. no to Linelist

**Comment by garimadosar5** [comment]
QA Notes - 
- Total children column is not clickable.
-
