### ISSUE TITLE
[JNPCT][Report] Children not weighed since last two visits

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#61]
Aggregate - https://docs.google.com/spreadsheets/d/1rilYb_F-zWMTyiYdXjHHmIoAiLCe_ok8/edit#gid=1122930447

Line List - https://docs.google.com/spreadsheets/d/1MIBqA9bNq-QUjYS8_NL5NVeBnhydoJVX/edit#gid=1897339731

**QA Checklist -** 
- [ ] Percentage Calculation
- [ ] Check for Column name and Indicator Name
- [ ] Check for 100% sun for percentage, if applicable
- [ ] All the filters are there.
- [ ] Line List - Check for all the columns
- [ ] Line List - Column names are, as mentioned in the requirement sheet.
- [ ] cases are pointed to UAT.

**Comment by 1t5j0y** [comment]
Increased column width in linelist to show full nutritional column header.
Added default start and end dates for the report to default to last 2 months data.
