### ISSUE TITLE
[JNPCT][Support] Issue in visit scheduling.

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#65]
https://avni.freshdesk.com/a/tickets/774

**Issue** -- For children around 24 months of age having nutritional status as normal, visits were getting missed.

**Acceptance criteria** -- At any age for children with nutritional status as **Normal** next visit should get scheduled as per the visit scheduling requirement.

**Comment by nupoorkhandelwal** [comment]
Fixed this on UAT.

**Comment by garimadosar5** [comment]
QA Notes - 
-  If a child followup is cancelled, it does not schedule a new followup visit. (It is scheduling cluster in charge visit if a cluster in charge visit gets cancelled.)
**Case -** Mayur Mahajan (admin@jnpctuat/password)
