### ISSUE TITLE
[JNPCT] Delivery form

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#7]
https://docs.google.com/spreadsheets/d/1rxddSJUw7vQ_6TEdPYkT5_fF0K8BUQajnIBum34dLqc/edit#gid=250852601

**Comment by shubhangipatil** [comment]
Skip Logic Pending For 
1.Week of Gestation
( if mother delivered before 36 week then it count as preterm ,Preterm or Full term show on the last page)

**Comment by garimadosar5** [comment]
QA Notes - 
- Place of delivery, 2 options as HOME and HOSPITAL and remove 'YET NOT DECIDED'.
- Date of discharge question is not showing.
- For the question "Number of days stayed at the hospital", logic is not right.
- Delivery complications, NONE can be selected with other options of the question.
- Option for Gender of newborn and stillborn is showing YES and NO.
- At the last page in system recommendation, It is showing `Very Preterm` and `preterm` for GA weeks 11. It should show only very `preterm`.

**Comment by garimadosar5** [comment]
@nupoorkhandelwal 

- Replace "Very Preterm" with Preterm. if GA Weeks<36.
