### ISSUE TITLE
Copy the forms that are meant for supervisors for arogya sahelis.

### ISSUE THREAD

**Issue by sachsk** [avniproject/jnpct#72]
- [x] Append Saheli to the name of these forms (ANC - Saheli)
- [x] Remove mandatory check

**Forms**

- [x] ANC - Saheli
- [x] Delivery form
- [x] Mother PNC
- [x] Mamta Divas child
- [x] Mamta Divas mother
- [x] Abortion 
- [x] Abortion followup
- [x] Delivery form
- [x] Child  Birth Form
- [x] Child pnc
- [x] child-Followup

sheet link: https://docs.google.com/spreadsheets/d/1EtliYSstTzmgeOAVhJDuVz7LlQYzeqq5/edit#gid=1245016898

**Comment by garimadosar5** [comment]
**QA Notes -** 
ANC - Saheli 
- Other complication? - Skip is not working.
Mamta Diwas Mother
- Did Mamta diwas held this month, this question should be added.
