### ISSUE TITLE
Saheli visit scheduling

### ISSUE THREAD

**Issue by sachsk** [avniproject/jnpct#73]
https://docs.google.com/spreadsheets/d/1EtliYSstTzmgeOAVhJDuVz7LlQYzeqq5/edit#gid=1245016898

**Comment by sachsk** [comment]
confusion in some scheduling needs to discuss with the client.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- For High risk pregnancies visits are not scheduling in 15 days. **We are taking the high risk from  form, not from decisions**
Case - Anita Chhajed.  
- What should be the scheduling for already enrolled women in pregnancy or PNC period.
- In supervisor scheduling if ANC 3 is scheduled for Sep but done in Aug then it again schedule the ANC 2 visit for Sep. But in Saheli it is scheduling based on last visit's earliest visit date time.
Case - seema panpatil
- Child PNC low birth is scheduled for the child. but child was not enrolled at the time of birth.
Also, low birth weight is not there for Saheli scheduling.
Case Sargam Rastogi.
