### ISSUE TITLE
Feedback 22-09-2021

### ISSUE THREAD

**Issue by sachsk** [avniproject/jnpct#75]
https://docs.google.com/spreadsheets/d/1hrABlhoXey4p_Dnur4FqnuOMhiENkIqVjfnhPMKHDvI/edit#gid=0

**Comment by garimadosar5** [comment]
QA Notes - 
- Case Antara Patel, there is visit schedule PNC-Saheli 9.

**Comment by garimadosar5** [comment]
QA Notes - 
- First it scheduled 9th PNC and then 8th PNC.
Case Antara Patel.
![Screenshot_2021-09-30-16-43-26-00.jpg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/e1983dcc-d6f1-45a2-857b-20d6e5953417)

**Comment by sachsk** [comment]
fixed this issue

**Comment by garimadosar5** [comment]
**QA Notes - 2**
- Supervisor should not be able to fill Saheli forms.
-  ![Screenshot_2021-10-04-11-34-32-32_e67de974eab1ae435bf1faa372eb4549.jpg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/bd56ff84-4d21-4c0d-ae3d-47f9c112e667)
- ![Screenshot_2021-10-04-11-34-45-06_e67de974eab1ae435bf1faa372eb4549.jpg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/0e0098b0-dd3b-4935-a70f-310d6d7de338)
- there is a birth form scheduled for ROSE DAVID and in profile it is shwing as overdue but this case is not there in Overdue box on home page. (For got schedule for today only)
- As a Saheli, I cannot see the DOB of child, it shows in weeks or month.
