### ISSUE TITLE
Aarogya Saheli TCR report																		

### ISSUE THREAD

**Issue by sachsk** [avniproject/jnpct#76]
ref doc: https://docs.google.com/spreadsheets/d/1EtliYSstTzmgeOAVhJDuVz7LlQYzeqq5/edit#gid=1635969381&range=B5:T5

**Comment by sachsk** [comment]
https://reporting-jasper.avniproject.org/jasperserver/flow.html?_flowId=viewReportFlow&_flowId=viewReportFlow&ParentFolderUri=%2FJNPCT%2FReports%2FAggregates&reportUnit=%2FJNPCT%2FReports%2FAggregates%2FSaheli_TCR_report&standAlone=true

**Comment by garimadosar5** [comment]
QA Notes - 
- In child Task generated "Birth forms" are not getting included. **Done**
Case - Antara Patel
- Case - Riya Bagga. there are severley underweight visits completed but not showing in the report. **Done**
