### ISSUE TITLE
UAT feedback

### ISSUE THREAD

**Issue by sachsk** [avniproject/jnpct#78]
- [x] Create a new Subject Village and create mamta diwas visit for that subject. Visit will be at the end of each month.

- [x]  Add new question for respiratory rate
    Respiration Rate - 
    - 0-59 days = 60 and above is HR.
    - 2 months to 1 year = 50 and above is high risk
    - More than 1 year = 40and above is High Risk
- [x] Hide unplanned visit except Delivery & abortion.Hide abortion & delivery if they filled once

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Create a visit after canceling. (Mamta diwas encounter) **DONE**
- Create the cancel form.  **DONE**
