### ISSUE TITLE
Uat feedback

### ISSUE THREAD

**Issue by sachsk** [avniproject/jnpct#81]
- [x] Add the traslation keys on lokalise

- [x] according age the respiratory rate should get red(40,50,60)

- [x] "Does the child has fast breathing" make autoselect based on age and respiratory rate in child followup
age <= 2 then above 59 is high.
age > 2 && age <= 12 then above 49 is high.
age > 12 then above 39 is high.

- [x] Show child followup in unplanned visits

**Comment by garimadosar5** [comment]
QA Notes - 
- Point 2. Please mention, what is the condition? when is it shown Red?
I cannot find where is it showing Red?
Also, confirm if this is required only for Saheli forms or supervisor forms also.
