### ISSUE TITLE
[JNPCT] Visit schedule change and some other changes.

### ISSUE THREAD

**Issue by sachsk** [avniproject/jnpct#82]
Ref ticket:  https://avni.freshdesk.com/a/tickets/1516

- [x] Child follow up visit is scheduling before 60 days of his pnc period, which not to be generated.
- [x] In high risk ANC  visit ANC 3 is not generated in many cases .
- [x] Question of MUAC in each ANC visit is not necessary, it should be ask first time only.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Fix MUAC in ANC saheli also. **Fixed**
- ANC 3 was scheduled on 21 dec and ANC 4 got scheduled on 14 Dec.
Case - Rama Patel 35 years, female
![Screenshot_2021-12-01-10-32-29-57.jpeg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/be245a7c-7479-4a9f-8a22-03f0df2b3bc5)
- giving this error on sync.
![Screenshot_2021-12-01-10-39-24-18_e67de974eab1ae435bf1faa372eb4549.jpeg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/f6b30126-838b-4310-b872-9cc93d41a375)

**Comment by sachsk** [comment]
While filling the encounters please change the emulator date
