### ISSUE TITLE
Live app feedback

### ISSUE THREAD

**Issue by sachsk** [avniproject/jnpct#83]
- [x] In child follow up form FEG "check for general danger symptoms" 
 a) is the child able to drink or breastfeed 
 b) does the child vomits everything? 
 c) has the child had convulsion ?
 d) see the child is lethargic or unconscious 

if any of these question answer is abnormal then the value of "Is there general danger sign" should be yes automatically.
make it autoselect and read only

**Comment by garimadosar5** [comment]
**QA Notes -** 
- Do this change for Saheli form also.
