### ISSUE TITLE
[JNPCT] Support ticket 1545

### ISSUE THREAD

**Issue by nupoorkhandelwal** [avniproject/jnpct#84]
Fix visit scheduling issues

- [x] Child PNC getting scheduled multiple times for same date. 
Case - .બેબી સીતારામ ધનગર, Female	17 Days	Kaprada, Rohiyal jangal, Suliya, Nirval

- [x]  CHILD FOLLOWUP scheduled for back date 01-08-2018
Case - નિરજ બાળુ ચોધરી, Male	4 Years	Kaprada, Rohiyal jangal, Motipalsan, Motipalsan-4
(check enrolment)

- [x] Fix visits/data generated due to these wrong visits.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- There is a child name "Rehan Siddiqui", weight is normal but created one visit as Chil PNC Low Birth.
and PNC 5 also generated same day. 
Check SS.
![IMG_20211230_153239.jpeg](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/6f868d75-3e70-4572-be59-542f950ff9a7)

**Comment by nupoorkhandelwal** [comment]
I have checked the visit scheduling for the above mentioned child and it is working right as per our visit scheduling logic. 
Since the child had low birth weight hence a Low birth Saheli visit got scheduled on the same day as Birth form encounter. And then with given set of next visits that was possible to schedule was on 10th day of birth , and hence PNC 5 was scheduled on 10th day of birth ie. 30th Dec.
