### ISSUE TITLE
Change in visit scheduling

### ISSUE THREAD

**Issue by sachsk** [avniproject/jnpct#85]
ticket:- https://avni.freshdesk.com/a/tickets/1569

Currently, we are scheduling only two Cluster incharge visits for children. now they want the multiple visit schedule based on the nutritional status of the child.

**Comment by sachsk** [comment]
ref doc:-https://docs.google.com/spreadsheets/d/1ifOuZrN3H7y05OIxTrIgYd7t9svqwUkN/edit#gid=1183256417


@sachsk  I do not have access to this doc.

**Comment by garimadosar5** [comment]
QA Notes - 
- If the child (Prashant Kumar) is 0-27 days then PNC 1 is getting scheduled but if the child  (Priti Sharwani) is more than 28 but less than 50 days of age, it directly scheduled PNC 3. By the logic PNC 1, it should generate PNC 2 for the second child.

 **Note** - {"name": "Child PNC 1", "earliest": 0, "max": 8},
		{"name": "Child PNC 2", "earliest": 28, "max": 36},
		{"name": "Child PNC 3", "earliest": 50, "max": 61}
**Not sure why it happened for child Prashant Kumar, i have tested it for two other children with same duration difference. Can you please test again?**

- Case - Prashant Kumar. After PNC CI-1 it scheduled CI followup 2. PNC CI 2 should be scheduled. - **Fixed**
- CI followup for2 months to 6 months is also not getting scheduled properly. **Fixed**
- We are not restricting visits to 2 visits, so remove number in visit name. Child followup CLuster Inchanrge - 1 **We are assigning Child followup CI 1& 2 for children 2 to 6 months. And then without number for 7 month onwards**
