### ISSUE TITLE
[JNPCT] Report Numbers Issue

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#86]
ticket - https://avni.freshdesk.com/a/tickets/1598

1. Child growth monitoring 7 months to 5 years - **Voided cases were included in the report. Added a check to exclude them**
a)	Latest Grade - SAM Number is not same as Mobile dashnoard.
 b)     SAM Line list - One child was showing that was dead and Death reported and showing in SAM Line List
c)       Child is in MAM but showing in SAM and Vice Versa.
(for b and c, client will share the name of cases).

2. Need to change High Risk criteria for high risk report. (Client will share the new criteria)  **Requirements not shared**
3. Delivery Care Report - 
	- Manual - April 01- Nov 30  - 1548 **1546 – Filter range: 1st April 12:00 a.m to 30th Nov 11:59 p.m.**
	- Report - 1534
4. Task generated and Task Completed Report - 
	- No Status - What cases are counting there? -
	- TCR for Arogya Saheli. - Not connected to LL - **Discussed with Dr. Sachin, its not needed.**

- [x]        - TCR Saheli add filter for date.

**Comment by utkarshavni** [comment]
Created a new issue for line item 2.  [https://app.zenhub.com/workspaces/avni-5cf8e458bf08585333fd64ac/issues/avniproject/jnpct/88](url)

**Comment by utkarshavni** [comment]
1.a.  Reports: SAM number is Total -25, Non exited – 22 in Aggregate report for Sildha. In offline dashboard it is 14.
1.b  Monika – Subject voided in app, no program exit form, In Reports it is shown in both SAM and removed from SAM line list.
1.c –  Piyush Magan – In App it is a voided case, Nutritional Status – SAM, Program Exit Reason – Other, Also having an entry in MAM – not voided

Khushi is MAM, showing in SAM. Does not have an entry in MAM line list Report while  In app it is MAM. 

2. Card Created for that.

3. The count I got was 1546 – Filter range: 1st April 12:00 a.m to 30th Nov 11:59 p.m.
For 1st April 12:00 a.m to 30th Nov 12 a.m – 1537

4. Not able to resolve.

**Comment by nupoorkhandelwal** [comment]
1. Jasper Report considers encounters -

- Child Followup
- Child Followup Cluster Incharge

While offline report card considers -

- 1. Child PNC Cluster Incahrge
- 2. Child Followup Cluster Incharge
- 3. Child PNC - Saheli
- 4. Child PNC Form
- 5. Child Followup
- 6. Child followup - Saheli
