### ISSUE TITLE
[JNPCT] Add option in cancel forms

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#87]
ticket - https://avni.freshdesk.com/a/tickets/1599
- [x] 1. Saheli visit cancel form - Add more options. Temporary Migration.
- [x] 2. Add Cancel option - Add Temporary Migration in all the form
- [x] 3. Move this to change to prod.

**Comment by garimadosar5** [comment]
**QA Notes -** 
- On cancelling ANC visit, next visit is getting scheduled on the same day.

**Comment by garimadosar5** [comment]
Option not added in following forms - 

- ANC - Saheli Encounter Cancellation
- Mother PNC -Saheli Encounter Cancellation
- Child PNC - Saheli Encounter Cancellation
- Child followup - Saheli Encounter Cancellation
- Birth form - Saheli Encounter Cancellation

**Comment by garimadosar5** [comment]
**QA Notes - 2**
Not added.
![Screen Shot 2022-02-22 at 9.48.42 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/f9ccfde2-f537-4449-9522-2144e0b509b7)

![Screen Shot 2022-02-22 at 9.49.12 AM.png](https://images.zenhubusercontent.com/5d0a151d5af8b352a1b5784b/270dcafc-214e-41f6-af19-ae884ea8d720)

**Comment by sachsk** [comment]
@garimadosar5 Changes are on UAT
