### ISSUE TITLE
[JNPCT] Visit Schedule - EC

### ISSUE THREAD

**Issue by garimadosar5** [avniproject/jnpct#9]
- Eligible couple followup

https://docs.google.com/spreadsheets/d/1rxddSJUw7vQ_6TEdPYkT5_fF0K8BUQajnIBum34dLqc/edit#gid=740855390

**Comment by nupoorkhandelwal** [comment]
**After get pregnant - Stop scheduling And again schedule the next visit after PNC/Abortion followup
Schedule next followup on the nearest date.**  >>>
** Right now, we cannot schedule visits for other program form current program visits **
