### ISSUE TITLE
[Ticket - App] Permenant migration in cancellation should stop visit scheduling.

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/jnpct#92]
In JNPCT, on cancellation of visits, when Permanent migration is selected in cancel reason, visit is scheduled right now.  Visit scheduling should stop in this case.

Ticket reference:
https://avni.freshdesk.com/a/tickets/1723

**Comment by nupoorkhandelwal** [comment]
Did this change for forms which had 'Permanent migration' as cancel reason.
