### ISSUE TITLE
[JNPCT] ANC visits are not scheduled for High risk pregnancy for Saheli

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/jnpct#94]
For high risk pregnancy, ANC visits are required to be scheduled every 15 days for Saheli, which are not scheduled right now.

**Comment by sachsk** [comment]
@utkarshavni 
i have checked the visit scheduling its working fine.
there is one question(Is the mother at high risk) in ANC form which needs to be filled to schedule high risk encounter.


Also informed to Dr.Sachin.
