### ISSUE TITLE
[JNPCT- Report] - Logic change for Saheli TCR report

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/jnpct#95]
Report link:
https://reporting-jasper.avniproject.org/jasperserver/flow.html?_flowId=viewReportFlow&_flowId=viewReportFlow&ParentFolderUri=%2FJNPCT%2FReports%2FAggregates&reportUnit=%2FJNPCT%2FReports%2FAggregates%2FSaheli_TCR_report&standAlone=true

Motivation:
The purpose of Aarogya Saheli TCR report is to help the program team in assessing how many of visits by Saheli are completed within Overdue date - this helps the team in disbursing payment at the end of every month to Sahelis based on their visits completion rate within overdue time period. Currently it shows all visits which are completed.

Goal:
There are two columns for each category of visit currently: "Tasks Generated" and "Tasks Completed". The "Tasks completed" should show number of visits which are completed before or on the overdue date by Aarogya Saheli User. The column name should also be changed to "Tasks completed in time".

Acceptance criteria:
The report should have two columns for each category of visits - "Tasks Generated" and "Tasks Completed in time". Tasks generated should show number of visits generated and "Tasks Completed in time" should show number of visits completed on or before overdue date. This must also reflect in the Percentage column.

**Comment by sachsk** [comment]
@nupoorkhandelwal **Total generated and total completed count not matching**



1- ANC Generated
`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1154 and i.is_voided=false;`

 2 - ANC completed
 `select count(*)
  from program_encounter enc
           left join individual i on i.id =enc.individual_id
  where encounter_type_id=1154 and i.is_voided=false and encounter_date_time notnull and encounter_date_time::date <= max_visit_date_time::date;`

 3 - mother pnc generated
 `select count(*)
  from program_encounter enc
           left join individual i on i.id =enc.individual_id
  where encounter_type_id=1155
    and  i.is_voided=false;`

4 - mother pnc completed
`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1155
   and  i.is_voided=false and encounter_date_time notnull  and encounter_date_time::date <= max_visit_date_time::date;`

5 - birth generated
`select count(*)
from program_encounter enc
         left join individual i on i.id =enc.individual_id
where encounter_type_id=1151
  and  i.is_voided=false;`

6 - birth completed
 `select    count(*)
from program_encounter enc
         left join individual i on i.id =enc.individual_id
where encounter_type_id=1151
  and  i.is_voided=false  and encounter_date_time notnull  and encounter_date_time::date <= max_visit_date_time::date;`

7 -child pnc generated ---10209---7795
`select count(*)
from program_encounter enc
         left join individual i on i.id =enc.individual_id
where encounter_type_id=1150
  and  i.is_voided=false
and  (extract(year from (age(current_date, date_of_birth))) * 12 +
    extract(month from (age(current_date, date_of_birth)))) <= 6
;
select count(*)
from program_encounter enc
         left join individual i on i.id =enc.individual_id
where encounter_type_id=1159
  and  i.is_voided=false
and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) <= 6;`

8 child pnc moderate---789--544

`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1150
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) <= 6
and enc.observations->>'3fb85722-fd53-43db-9e8b-d34767af9f7e'='Moderately Underweight'
   and encounter_date_time::date<= max_visit_date_time::date
;`
`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1159
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) <= 6
and enc.observations->>'68a6a336-4a91-468b-9b7d-ff37e637f5b7'='Moderately Underweight' and encounter_date_time::date<= max_visit_date_time::date
;`

9 child pnc normal---3605--1031


`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1150
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) <= 6
   and enc.observations->>'3fb85722-fd53-43db-9e8b-d34767af9f7e'='Normal'
   and encounter_date_time::date<= max_visit_date_time::date
;`
`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1159
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) <= 6
   and enc.observations->>'68a6a336-4a91-468b-9b7d-ff37e637f5b7'='Normal' and encounter_date_time::date<= max_visit_date_time::date
;`




9 child pnc severe---714--276


`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1150
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) <= 6
   and enc.observations->>'3fb85722-fd53-43db-9e8b-d34767af9f7e'='Severely Underweight'
   and encounter_date_time::date<= max_visit_date_time::date`;
`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1159
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) <= 6
   and enc.observations->>'68a6a336-4a91-468b-9b7d-ff37e637f5b7'='Severely Underweight' and encounter_date_time::date<= max_visit_date_time::date
;`

10   child followup


`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1159
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) >=
         7 and
          (extract(year from (age(current_date, date_of_birth))) * 12 +
           extract(month from (age(current_date, date_of_birth)))) <=
          60 ;`


11   child followup sam


`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1159
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) >=
         7 and
          (extract(year from (age(current_date, date_of_birth))) * 12 +
           extract(month from (age(current_date, date_of_birth)))) <=
          60
and enc.observations->>'3fb85722-fd53-43db-9e8b-d34767af9f7e'='SAM'
   and encounter_date_time::date<= max_visit_date_time::date
;`



12   child followup mam


`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1159
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) >=
         7 and
          (extract(year from (age(current_date, date_of_birth))) * 12 +
           extract(month from (age(current_date, date_of_birth)))) <=
          60
and enc.observations->>'3fb85722-fd53-43db-9e8b-d34767af9f7e'='MAM'
   and encounter_date_time::date<= max_visit_date_time::date
;`

13   child followup normal


`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1159
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) >=
         7 and
          (extract(year from (age(current_date, date_of_birth))) * 12 +
           extract(month from (age(current_date, date_of_birth)))) <=
          60
and enc.observations->>'3fb85722-fd53-43db-9e8b-d34767af9f7e'='Normal'
   and encounter_date_time::date<= max_visit_date_time::date
;`

**Comment by sachsk** [comment]
@nupoorkhandelwal **Total generated and total completed count not matching**



1- ANC Generated
`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1154 and i.is_voided=false;`

 2 - ANC completed
 `select count(*)
  from program_encounter enc
           left join individual i on i.id =enc.individual_id
  where encounter_type_id=1154 and i.is_voided=false and encounter_date_time notnull and encounter_date_time::date <= max_visit_date_time::date;`

 3 - mother pnc generated
 `select count(*)
  from program_encounter enc
           left join individual i on i.id =enc.individual_id
  where encounter_type_id=1155
    and  i.is_voided=false;`

4 - mother pnc completed
`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1155
   and  i.is_voided=false and encounter_date_time notnull  and encounter_date_time::date <= max_visit_date_time::date;`

5 - birth generated
`select count(*)
from program_encounter enc
         left join individual i on i.id =enc.individual_id
where encounter_type_id=1151
  and  i.is_voided=false;`

6 - birth completed
 `select    count(*)
from program_encounter enc
         left join individual i on i.id =enc.individual_id
where encounter_type_id=1151
  and  i.is_voided=false  and encounter_date_time notnull  and encounter_date_time::date <= max_visit_date_time::date;`

7 -child pnc generated ---10209---7795
`select count(*)
from program_encounter enc
         left join individual i on i.id =enc.individual_id
where encounter_type_id=1150
  and  i.is_voided=false
and  (extract(year from (age(current_date, date_of_birth))) * 12 +
    extract(month from (age(current_date, date_of_birth)))) <= 6
;
select count(*)
from program_encounter enc
         left join individual i on i.id =enc.individual_id
where encounter_type_id=1159
  and  i.is_voided=false
and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) <= 6;`

8 child pnc moderate---789--544

`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1150
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) <= 6
and enc.observations->>'3fb85722-fd53-43db-9e8b-d34767af9f7e'='Moderately Underweight'
   and encounter_date_time::date<= max_visit_date_time::date
;`
`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1159
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) <= 6
and enc.observations->>'68a6a336-4a91-468b-9b7d-ff37e637f5b7'='Moderately Underweight' and encounter_date_time::date<= max_visit_date_time::date
;`

9 child pnc normal---3605--1031


`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1150
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) <= 6
   and enc.observations->>'3fb85722-fd53-43db-9e8b-d34767af9f7e'='Normal'
   and encounter_date_time::date<= max_visit_date_time::date
;`
`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1159
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) <= 6
   and enc.observations->>'68a6a336-4a91-468b-9b7d-ff37e637f5b7'='Normal' and encounter_date_time::date<= max_visit_date_time::date
;`




9 child pnc severe---714--276


`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1150
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) <= 6
   and enc.observations->>'3fb85722-fd53-43db-9e8b-d34767af9f7e'='Severely Underweight'
   and encounter_date_time::date<= max_visit_date_time::date`;
`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1159
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) <= 6
   and enc.observations->>'68a6a336-4a91-468b-9b7d-ff37e637f5b7'='Severely Underweight' and encounter_date_time::date<= max_visit_date_time::date
;`

10   child followup


`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1159
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) >=
         7 and
          (extract(year from (age(current_date, date_of_birth))) * 12 +
           extract(month from (age(current_date, date_of_birth)))) <=
          60 ;`


11   child followup sam


`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1159
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) >=
         7 and
          (extract(year from (age(current_date, date_of_birth))) * 12 +
           extract(month from (age(current_date, date_of_birth)))) <=
          60
and enc.observations->>'3fb85722-fd53-43db-9e8b-d34767af9f7e'='SAM'
   and encounter_date_time::date<= max_visit_date_time::date
;`



12   child followup mam


`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1159
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) >=
         7 and
          (extract(year from (age(current_date, date_of_birth))) * 12 +
           extract(month from (age(current_date, date_of_birth)))) <=
          60
and enc.observations->>'3fb85722-fd53-43db-9e8b-d34767af9f7e'='MAM'
   and encounter_date_time::date<= max_visit_date_time::date
;`

13   child followup normal


`select count(*)
 from program_encounter enc
          left join individual i on i.id =enc.individual_id
 where encounter_type_id=1159
   and  i.is_voided=false
   and   (extract(year from (age(current_date, date_of_birth))) * 12 +
          extract(month from (age(current_date, date_of_birth)))) >=
         7 and
          (extract(year from (age(current_date, date_of_birth))) * 12 +
           extract(month from (age(current_date, date_of_birth)))) <=
          60
and enc.observations->>'3fb85722-fd53-43db-9e8b-d34767af9f7e'='Normal'
   and encounter_date_time::date<= max_visit_date_time::date
;`

**Comment by nupoorkhandelwal** [comment]
**@sachsk please remember to set the timezone before testing the count**
set timezone to 'Asia/Kolkata';

**Comment by AchalaBelokar** [comment]
1) In the Saheli TCR report Children 7 months -5 years 
The total no of tasks generated was 69716 and 
Saheli task generated  child followup count is 69717

**Comment by AchalaBelokar** [comment]
1. In the Saheli TCR report Children ANC Task generated 8530 and 
2. Saheli task generated ANC the count is 8531

**Comment by AchalaBelokar** [comment]
Saheli task generated PNC count is 6891 
Saheli TCR report PNC generated count is 6890
