### ISSUE TITLE
[JNPCT] Offline Dashboard change - High Risk ANC

### ISSUE THREAD

**Issue by utkarshavni** [avniproject/jnpct#99]
Offline Dashboard change

- [ ] Cluster incharge - 

Indicator - "High Risk - ANC"
Currently indicator for High risk pregnancy also displays the count of women who were high risk but delivery has happened - it should only show the count of active high risk pregnancy and not include the women for whom delivery has already been recorded.

**Comment by sachsk** [comment]
we already added this check in report.
i have tested on uat and it working correctly

**Comment by sachsk** [comment]
These changes are already on prod.
Closing this issue
